/*
 * 88pm860x-audio.h  --  audio driver for pm860x audio
 *
 * Copyright (C) 2007 Marvell International Ltd.
 * Author: Paul Shen <bshen9@marvell.com>
 *         Bin Yang <bin.yang@marvell.com>
 *				 Yael Sheli Chemla<yael.s.shemla@marvell.com>
 *
 *  This program is free software; you can redistribute  it and/or modify it
 *  under  the terms of  the GNU General  Public License as published by the
 *  Free Software Foundation;  either version 2 of the  License, or (at your
 *  option) any later version.
 *
 */

#ifndef __PM860X_AUDIO_H
#define __PM860X_AUDIO_H

/* pm860x audio register start space */
#define PM860X_AUDIO_GROUP_A_FIRST_REG 0x40
#define PM860X_AUDIO_GROUP_B_FIRST_REG 0xB0

/* pm860x audio clk related register */
#define MISC1		          0x00
#define MCLK		          0x01
#define MISC2		          0x02
#define PLL_CTRL1	          0x03
#define PLL_FRAC1	          0x04
#define PLL_FRAC2	          0x05
#define PLL_FRAC3	          0x06
#define SAMPLE_RATE_SWITCH	  0x07

#define PM860X_AUDIO_GROUP_B_OFFSET_START    (SAMPLE_RATE_SWITCH + 1) /* 0x8 */

#define PCM_INTERFACE1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x00)
#define PCM_INTERFACE2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x01)
#define PCM_INTERFACE3	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x02)
#define ADC_PCM	              (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x03)
#define	ECHO_CANCEL_PATH      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x04)
#define SIDETONE_GAIN1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x05)
#define SIDETONE_GAIN2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x06)
#define SIDETONE_GAIN3	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x07)
#define ADC_OFFSET1	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x08)
#define ADC_OFFSET2	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x09)
#define DMIC_DELAY	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x0a)
#define I2S_INTERFACE_1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x0b)
#define I2S_INTERFACE_2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x0c)
#define I2S_INTERFACE_3	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x0d)
#define I2S_INTERFACE_4	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x0e)
#define EQUALIZER_N0_1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x0f)
#define EQUALIZER_N0_2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x10)
#define EQUALIZER_N1_1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x11)
#define EQUALIZER_N1_2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x12)
#define EQUALIZER_D1_1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x13)
#define EQUALIZER_D1_2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x14)
#define SIDE_TONE_1	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x15)
#define SIDE_TONE_2	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x16)
#define LEFT_GAIN1	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x17)
#define LEFT_GAIN2	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x18)
#define RIGHT_GAIN1	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x19)
#define RIGHT_GAIN2	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x1a)
#define DAC_OFFSET	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x1b)
#define OFFSET_LEFT1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x1c)
#define OFFSET_LEFT2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x1d)
#define OFFSET_RIGHT1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x1e)
#define OFFSET_RIGHT2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x1f)
#define ADC_ANALOG_PROGRAM1   (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x20)
#define ADC_ANALOG_PROGRAM2   (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x21)
#define ADC_ANALOG_PROGRAM3   (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x22)
#define ADC_ANALOG_PROGRAM4   (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x23)
#define ANALOG_TO_ANALOG      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x24)
#define HS1_CTRL	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x25)
#define HS2_CTRL	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x26)
#define LO1_CTRL	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x27)
#define LO2_CTRL	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x28)
#define EAR_SPKR_CTRL1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x29)
#define EAR_SPKR_CTRL2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x2a)
#define AUDIO_SUPPLIES1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x2b)
#define AUDIO_SUPPLIES2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x2c)
#define ADC_ENABLES1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x2d)
#define ADC_ENABLES2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x2e)
#define DAC_ENABLES1	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x2f)
#define DUMMY		          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x30)
#define DAC_ENABLES2	      (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x31)
#define AUDIO_CAL1	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x32)
#define AUDIO_CAL2	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x33)
#define AUDIO_CAL3	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x34)
#define AUDIO_CAL4	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x35)
#define AUDIO_CAL5	          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x36)
#define ANALOG_INPUT_SEL1     (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x37)
#define ANALOG_INPUT_SEL2     (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x38)
#define PCM_INTERFACE4        (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x39)
#define I2S_INTERFACE_5       (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x3a)
#define SHORTS		          (PM860X_AUDIO_GROUP_B_OFFSET_START + 0x3b)

#define PM860X_AUDIO_GROUP_B_OFFSET_END    SHORTS  /*0x43 = 67 */

/* pm860x audio register end space */
#define PM860X_AUDIO_GROUP_A_LAST_REG	(PM860X_AUDIO_GROUP_A_FIRST_REG + PM860X_AUDIO_GROUP_B_OFFSET_START - 1)
#define PM860X_AUDIO_GROUP_B_LAST_REG	(PM860X_AUDIO_GROUP_B_FIRST_REG + PM860X_AUDIO_GROUP_B_OFFSET_END - PM860X_AUDIO_GROUP_B_OFFSET_START)

extern struct snd_soc_dai pm860x_audio_dai[];
extern struct snd_soc_codec_device soc_codec_dev_pm860x_audio;

#endif
