/*
 * This software program is licensed subject to the GNU General Public License
 * (GPL).Version 2,June 1991, available at http://www.fsf.org/copyleft/gpl.html

 * (C) Copyright 2007 Marvell International Ltd.
 * All Rights Reserved
 */

#ifndef PXA_MIPS_RAM_H
#define PXA_MIPS_RAM_H

#include <linux/mipsram.h>

/* definitions for MIPS RAM calls */
enum {
	PP_D0CS_MIPS_RAM = 0,
	PP_PP1_MIPS_RAM,
	PP_PP2_MIPS_RAM,
	PP_PP3_MIPS_RAM,
	PP_PP4_MIPS_RAM,
	PP_PP5_MIPS_RAM,
	PP_PP_CUSTOM_MIPS_RAM,
	PP_PP_BOOT_MIPS_RAM,
	ACIPC_DDR_REQ_RECEIVED_MIPS_RAM,
	ACIPC_DVFM_CONSTRAITNS_SET,
	ACIPC_DDR_REL_RECEIVED_MIPS_RAM,
	ACIPC_DVFM_CONSTRAITNS_RELEASED,
	EARLY_DDR_PREVENTING_D0CS,
	ACIPC_HF_DDR_REQ_RECEIVED_MIPS_RAM,
	ACIPC_HF_DDR_REQ_HANDHELD_MIPS_RAM,
	ACIPC_HF_DDR_REL_RECEIVED_MIPS_RAM,
	ACIPC_HF_DDR_REL_HANDHELD_MIPS_RAM,
	MAX_NUMBER_OF_PP_MIPS_RAM,
	INVALID_PP_NUMBER_MIPS_RAM = 0xFF
};

#define OFFSET_LPM_MIPS_RAM 0x100

enum {
	ENTER_IDLE_MIPS_RAM = OFFSET_LPM_MIPS_RAM,
	EXIT_IDLE_MIPS_RAM,
	ENTER_D2_MIPS_RAM,
	EXIT_D2_MIPS_RAM,
	ENTER_CGM_MIPS_RAM,
	EXIT_CGM_MIPS_RAM,
	ENTER_D1_MIPS_RAM,
	EXIT_D1_MIPS_RAM,
	LPM_TRACE_MAX_NUMBER_MIPS_RAM,
	INVALID_LPM_NUMBER_MIPS_RAM = 0x1FF,
};

#endif
